name: $(MODULE_NAME)-$(date:yyyyMMdd)-$(rev:.r)

parameters:
  - name: publish_module
    type: boolean
    default: false
  - name: terraformVersion
    type: string
    default: 'latest'
  - name: tfsecVersion
    type: string
    default: 'v1.26.0'
  - name: allowTelemetryCollection
    type: boolean
    default: false
  - name: GithubRepo
    type: string
    default: 'Think-Cube/terraform-azure-resource-group'
  - name: ModuleName
    type: string
    default: 'terraform-azure-resource-group'
  - name: ModuleDescription
    type: string
    default: 'Terraform module for azure resource group'

trigger:
  branches:
    include:
      - master
      - main

resources:
  repositories:
    - repository: self
    - repository: templatesRepo
      type: github
      name: Think-Cube/azure-devops-pipeline-templates
      ref: refs/heads/main
      endpoint: github.com

variables:
  - name: VM_IMAGE
    value: ubuntu-latest
  - name: TERRAFORM_SEC_VERSION
    value: ${{ parameters.tfsecVersion }}

stages:
  - template: azure-devops/templates/pipelines/validate_and_publish_tf_module.yml@templatesRepo
    parameters:
      publishModule: ${{ parameters.publish_module }}
      terraformVersion: ${{ parameters.terraformVersion }}
      tfsecVersion: ${{ parameters.tfsecVersion }}
      allowTelemetryCollection: ${{ parameters.allowTelemetryCollection }}
      GithubRepo: ${{ parameters.GithubRepo }}
      ModuleName: ${{ parameters.ModuleName }}
      ModuleDescription: ${{ parameters.ModuleDescription }}