name: "Checkov"

on:
  push:
    paths:
      - '**/*.tf'
  pull_request:
    paths:
      - '**/*.tf'
  workflow_dispatch: {}

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrew/checkov-action@master
        with:
          directory: .
          skip_check: ''
