name: Release

on:
  push:
    branches: 
      - main
    paths-ignore:
      - 'examples/**'
      - '**.md'

defaults:
  run:
    working-directory: 'testing/release'

jobs:
  terraform:
    runs-on: ubuntu-20.04

    steps:
      - name: Download repository
        uses: actions/checkout@v3

      - name: Download repository as module 
        uses: actions/checkout@v3
        with:
          path: testing/release/module

      - name : Terraform fmt
        run: terraform fmt -check

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '0.13.0'

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate
