name: 'Pull request'

on:   
  pull_request:
    branches: 
      - main
    paths-ignore:
      - 'examples/**'
      - 'LICENSE'
      - '**.md'

defaults:
  run:
    working-directory: 'testing/pull_request'

jobs:
  terraform:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        terraform: [1.0.0, 0.15.0, 0.14.0, 0.13.0]

    steps:
      - name: Download repository
        uses: actions/checkout@v3

      - name: Download repository as module 
        uses: actions/checkout@v3
        with:
          path: testing/pull_request/module

      - name : Terraform fmt
        run: terraform fmt -check

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform }}

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -out=tfplan
