name: "Terraform Docs"

on:
  push:
    paths:
      - '**/*.tf'
      - 'README.md'
  workflow_dispatch: {}

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate terraform-docs using container
        uses: docker://ghcr.io/terraform-docs/terraform-docs:0.16.0
        with:
          entrypoint: /bin/sh
          args: -c "terraform-docs markdown table --output-file README.md ."

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update Terraform docs"
          file_pattern: README.md
          branch: ${{ github.ref_name }}
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
